spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis: 
  mapper-locations: classpath:com/nit/weibo/mapper/*.xml
  type-aliases-package: classpath:com.nit.weibo.dao
    