spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis: 
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.nit.weibo.model

  #pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    